### ISSUE TITLE
Using Character prefs randomly stops working

### ISSUE THREAD

**Issue by itsmeow** [Rukofamicom/Royale-Station-13#20]
Sometimes, after editing your character, you can no longer click on any of the buttons in character setup, they won't perform Topic calls.

**Comment by itsmeow** [comment]
Seems related to hitting Save Setup.

Probably a database latency issue

**Comment by Rukofamicom** [comment]
This is a database issue, yes. I'm unsure of how to resolve it because it's not an issue Bee seems to have. There's never any runtimes or error logs for me to go off of, and as far as I can tell it generally only happens during server set-up. 

It also curiously only seems to happen the very first time a save is attempted per hard reboot, not even per character just as a whole. Making a purchase pushes to the database and lags it, but subsequent database access has no issues.

**Comment by itsmeow** [comment]
This was fixed by updating DB configs serverside
